---
title: "English"
format: html
editor: visual
---

# Emilia S. Löscher {style="color: #258c90"}

::: center
[e.s.loscher\@students.uu.nl](mailto:e.s.loscher@students.uu.nl) \| [GitHub](https://github.com/emsulo) \| [LinkedIn](https://www.linkedin.com/in/emilia-l%C3%B6scher-1b5717249/)
:::

# Education {style="color: #258c90"}

::: grid
::: {.g-col-4 style="color: black"}
09/2021 - 06/2023
:::

::: {.g-col-8 style="color: black"}
**Utrecht University (UU)** \| Utrecht, The Netherlands

Research Master: Methodology and Statistics for the Behavioural, Biomedical and Social Sciences
:::

::: {.g-col-4 style="color: black"}
09/2018 - 04/2019
:::

::: {.g-col-8 style="color: black"}
**University of Victoria (UVIC)** \| Victoria, Canada

Exchange during B.Sc. in Statistics at TU Dortmund
:::

::: {.g-col-4 style="color: black"}
10/2017 - 08/2021
:::

::: {.g-col-8 style="color: black"}
**TU Dortmund University** \| Dortmund, Germany

B.Sc. in Statistics, Minor in "Theoretical Medicine"

Grade: 1.8
:::

::: {.g-col-4 style="color: black"}
08/2009 - 06/2017
:::

::: {.g-col-8 style="color: black"}
**Gymnasium Essen-Werden** \| Essen, Germany

High School with Abitur

Grade: 1.0
:::
:::

# Experience {style="color: #258c90"}

::: grid
::: {.g-col-4 style="color: black"}
04/2021 - 08/2021
:::

::: {.g-col-8 style="color: black"}
#### TU Dortmund University \| Dortmund, Germany

Student assistant in the context of the **Research Training Group 2624** "Biostatistical Methods for High-Dimensional Data in Toxicology"    
- Working on code for a simulation study in R
:::

::: {.g-col-4 style="color: black"}
07/2020 - 08/2021
:::

::: {.g-col-8 style="color: black"}
#### TU Dortmund University \| Dortmund, Germany

Student assistant at **Advisory Service** of the Department of Statistics

\- Answering questions regarding offered programs of the department

\- Answering questions regarding eligibility, application, enrollment and visa issues for international students (English)
:::

::: {.g-col-4 style="color: black"}
12/2017 - 08/2018 & 08/2019 - 12/2020
:::

::: {.g-col-8 style="color: black"}
#### Institute of Medical Informatics, Biometry und Epidemiology (IMIBE) \| Essen, Germany

Student assistant

\- Data entry for the "Heinz Nixdorf Recall Studie" and "Heinz Nixdorf Recall MehrGenerationenStudie"

\- Working with Microsoft Access
:::
:::

# Proficiencies {style="color: #258c90"}

## (Statistical) Programming Languages {style="color: black"}

-   R: profound knowledge

-   Rmarkdown and Quarto: good knowledge

-   Python: basic knowledge

-   LaTeX: good knowledge


## Languages {style="color: black"}

-   German: native

-   English: full professional proficiency TOEFL iBT: Score 115/120 in June 2021

-   Dutch: limited working proficiency

-   French: Elementary proficiency

# Achievements {style="color:  #258c90"}
 
:::grid 
::: {.g-col-12 style="color: black"}
-   DAAD PROMOS scholarship

-   Participant in bilateral oversea exchange program between TU Dortmund University, Germany, and University of Victoria, Canada

-   High school student participant in Research Training Group 2098 (GRK 2098)     "Biomedicine of the acid sphingomyelinase/acid ceramidase system"
:::
:::